export { default as Dashboard } from "./Dashboard";
export { default as MyExchanges } from "./MyExchanges";
export { default as SignIn } from "./SignIn/SignIn";
export { default as SignUp } from "./SignUp/SignUp";
export { default as Billing } from "./Billing";
export { default as Referrals } from "./Referrals";
export { default as Settings } from "./Settings";
export { default as ManageCopyTrading } from "./ManageCopyTrading";
export { default as MarketPlace } from "./MarketPlace";
